ARG BASE_IMAGE=docker.io/amd64/ubuntu:24.04
FROM ${BASE_IMAGE}
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    systemd systemd-sysv dbus dbus-x11 libgtk-3-0t64 libexpat1 zlib1g \
    xvfb xauth polkitd pkexec libglib2.0-bin at-spi2-core fonts-dejavu-core weston \
    libalut0 libopenal1 libxmu6 libxpm4 libxaw7 libxft2 libxxf86vm1 gedit
STOPSIGNAL SIGRTMIN+3
ENTRYPOINT ["/sbin/init"]
